import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import Providers from "./providers";
import GlobalContextProvider from "@/contexts/GlobalContext";
import "./globals.css";

// import {
//   dehydrate,
//   HydrationBoundary,
//   QueryClient,
// } from "@tanstack/react-query";

// import { getCurrentUser } from "@/lib/firebase/firebase-admin";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const queryClient = new QueryClient();

  // await queryClient.prefetchQuery({
  //   queryKey: ["user"],
  //   queryFn: getCurrentUser,
  // });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <HydrationBoundary state={dehydrate(queryClient)}> */}
          <GlobalContextProvider>{children}</GlobalContextProvider>
          {/* </HydrationBoundary> */}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
