import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReCaptchaProvider } from "next-recaptcha-v3";
import { Toaster } from "@/components/ui/toaster";
import Providers from "./providers";
import GlobalContextProvider from "@/contexts/GlobalContext";
import { ThemeProvider } from "@/components/ui/theme-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReCaptchaProvider
          reCaptchaKey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        >
          <Providers>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <GlobalContextProvider>{children}</GlobalContextProvider>
            </ThemeProvider>
            <Toaster />
          </Providers>
        </ReCaptchaProvider>
      </body>
    </html>
  );
}
